# this file is a helper to run all the supported dbs locally, the data is ephemeral since no host volumes will be mounted
version: "3.6"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"
    restart: always
  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    restart: always
